FROM nginx:alpine 

WORKDIR /app

COPY index.html /usr/share/nginx/html/index.html

# Documentas que el contenedor expondrá ese puerto interno por def nginx es 80
# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]



