services:
  db:
    image: postgres:15-alpine
    container_name: db-prueba
    environment:
      - POSTGRES_PASSWORD=1234
    networks:
      - red-practica

    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 2s
          timeout: 2s
          retries: 5

  # Servicio temporal que automatiza la prueba
  tester:
    image: alpine
    command: ping -c 4 db-prueba  # Ejecuta 4 pings al hostname y finaliza
    depends_on:
      db:
        condition: service_healthy # Espera a que la BD esté lista antes de testear
    networks:
      - red-practica


networks:
  red-practica:
    name: red-practica
    driver: bridge

#Para ejecutar este compose
# docker compose up --exit-code-from tester --build && docker compose down -v