services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mi_api_python
    ports:
      - "8000:8000"
    environment:
      - APP_WORKERS=1
    # Opcional para desarrollo: recarga en vivo sin reconstruir la imagen
    # volumes:
    #   - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 1 