services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: db-prueba
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - red-app
    volumes:
      - datos_db:/var/lib/postgresql/data

    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
          interval: 2s
          timeout: 2s
          retries: 5

  # Servicio temporal que automatiza la prueba
  redis:
    image: redis:7-alpine
    container_name: mi-redis
    depends_on:
      db: 
        condition: service_healthy
    networks:
      - red-app

volumes:
  datos_db:     

networks:
  red-app:
    name: red-app
    driver: bridge

